#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "example"
name = "Example app"
description.en = "Explain in *a few (10~15) words* the purpose of the app or what it actually does (it is meant to give a rough idea to users browsing a catalog of 100+ apps)"
description.fr = "Expliquez en *quelques* (10~15) mots l'utilité de l'app ou ce qu'elle fait (l'objectif est de donner une idée grossière pour des utilisateurs qui naviguent dans un catalogue de 100+ apps)"

version = "1.0~ynh1"

maintainers = ["eric_G"]

[upstream]
# NB: Only the "license" key is mandatory. Remove entries for which there's no relevant data
license = "free" # you can see the available licenses identifiers list here: https://spdx.org/licenses/
website = "https://example.com"
demo = "https://demo.example.com"
admindoc = "https://docs.movary.org/install/manual/"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/leepeuker/movary/"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/leepeuker/movary/archive/refs/tags/0.64.1.tar.gz"
    sha256 = "52785adc49dc7b6db7885dd8ad7e92b430ceb172b159446ec51d97c6e65bce3e"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.4-mysql, php8.4-mbstring, php8.4-simplexml, php8.4-pecl-imagick"

    [resources.database]
    type = "mysql"
