#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "movary"
name = "Movary"
description.en = "web app to track and rate your watched movies "
description.fr = "Application web pour suivre et évaluer les films que vous avez regardés"

version = "0.64.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "free"
website = "https://example.com"
demo = "https://demo.example.com"
admindoc = "https://docs.movary.org/install/manual/"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/leepeuker/movary/"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/leepeuker/movary/archive/refs/tags/0.64.1.tar.gz"
    sha256 = "52785adc49dc7b6db7885dd8ad7e92b430ceb172b159446ec51d97c6e65bce3e"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.4-sqlite3, php8.4-mysql, php8.4-mbstring, php8.4-simplexml"

    [resources.database]
    type = "mysql"
